=== Kemp-J/dfc-data/Schemas/civilian/civilian_ship.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dfc/schemas/civilian/civilian_ship.json",
    "title": "DFC Civilian Ship Data",
    "description": "Data file for a civilian ship class. Identical to the fleet ship format except points may be null for scenario-only ships.",
    "type": "object",
    "required": [
        "Class",
        "Type",
        "Points",
        "Tonnage",
        "BaseSize",
        "Profile",
        "Weapons",
        "Load",
        "KnownShips",
        "Flavour"
    ],
    "additionalProperties": false,
    "properties": {
        "Class":             { "type": "string" },
        "Type":              { "type": "string" },
        "Points":            { "type": ["integer", "null"] },
        "Tonnage":           { "$ref": "https://dfc/schemas/defs.json#/$defs/Tonnage" },
        "BaseSize":          { "type": "integer" },
        "CountsForTonnageSpend": { "type": "boolean", "default": true },
        "CanAssignAdmiral":      { "type": "boolean", "default": true },
        "Profile":           { "$ref": "https://dfc/schemas/defs.json#/$defs/ShipProfile" },
        "AsIfSpecial":       { "$ref": "https://dfc/schemas/defs.json#/$defs/AsIfSpecial" },
        "Weapons":           { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Weapon" } },
        "Load":              { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/LoadEntry" } },
        "Upgrades":          { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/UpgradeEntry" } },
        "Rules":             { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Rule" } },
        "AdmiralAbilities":  { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Ability" } },
        "UsableIn":          { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/UsableInEntry" } },
        "KnownShips":        { "type": "array", "items": { "type": "string" } },
        "Flavour":           { "type": "string" }
    }
}

=== Kemp-J/dfc-data/Data/Civilian/mk_mass_transporter.json
{
    "Class": "MK Mass Transporter",
    "Type": "Civilian Hauler",
    "Points": 41,
    "Tonnage": "L",
    "BaseSize": 30,
    "Profile": {
        "Thrust": 10,
        "Scan": 4,
        "Sig": 4,
        "Hull": 5,
        "ES": "5+",
        "KS": "6+",
        "BS": "-",
        "G": "1-2",
        "Special": [
            "Boardable",
            "Descent",
            "Rare"
        ]
    },
    "Weapons": [
        {
            "Name": "Deterrence Missiles",
            "Arc": "F/S",
            "Att": 4,
            "Lock": "3+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Close Action"
            ]
        }
    ],
    "Load": [],
    "Rules": [
        {
            "Name": "Mercenary",
            "Text": "This Ship may be used in any Fleet regardless of faction. When taken as part of your fleet, this Ship loses its Boardable rule."
        },
        {
            "Name": "Bulk Lighter",
            "Text": "While a Ship with this rule is on the table, you have access to the following Ability:\nBattalion Support (1AP): Once per activation, when you deploy Battalions from a Group on any Orbital Layer within 6\" of a friendly Ship with the Bulk Lighter rule, choose one of the launching Asset types. If the chosen Asset is either Dropships or Drop Pods, place an additional Battalion. If the chosen Asset is Bulk Landers, place an additional two Battalions. Other Launch Assets are unaffected by this Ability."
        }
    ],
    "AdmiralAbilities": [
        {
            "Cost": "1AP",
            "Name": "Battalion Support",
            "Effect": "Once per activation, when you deploy Battalions from a Group on any Orbital Layer within 6\" of a friendly Ship with the Bulk Lighter rule, choose one of the launching Asset types. If the chosen Asset is either Dropships or Drop Pods, place an additional Battalion. If the chosen Asset is Bulk Landers, place an additional two Battalions. Other Launch Assets are unaffected by this Ability."
        }
    ],
    "UsableIn": [
        {
            "Fleet": "*",
            "Modifiers": [
                {
                    "Target": "Special",
                    "Type": "remove",
                    "Value": "Boardable"
                }
            ]
        }
    ],
    "KnownShips": [],
    "Flavour": "It's a tough, thankless job hauling cargo from ground to space, but the Maganum Kinematics Mass Transporter takes it all in its stride. This reliable workhorse can be frequently seen flitting between orbit and atmosphere collecting and dispensing valuable cargo. During the reconquest, the durable, yet lightly armoured spaceframe of this vessel was used as a second line support vessel assisting troopships in setting up forward operating bases. Full of prefabricated barricades, fire-support bunkers, and even command centres, this small hauler vastly improves the efficiency of troops deployed to combat zones. Keeping the war machine well equipped, well stocked, and with a relatively comfortable, if cramped base to strike out at Scourge targets from.\nEven though their primary contracts are with the UCM, Maganum Kinematics have sold many of these to other non government organisations. Various shipping magnates operate at least one of these reliable ships at each of their destinations. More surprisingly, even other factions have been making use of these vessels. The PHR stationed at Earth have requisitioned a pair of these ships, as well as Kalium counting no fewer than four of these vessels amongst its fleet, though only two have been seen operating in the vicinity of Earth."
}

=== Kemp-J/dfc-data/Data/Scourge/daemon.json
{
    "Class": "Daemon",
    "Type": "Battleship",
    "Points": 215,
    "Tonnage": "H",
    "BaseSize": 50,
    "Profile": {
        "Thrust": 8,
        "Scan": 8,
        "Sig": 10,
        "Hull": 20,
        "ES": "3+",
        "KS": "4+",
        "BS": "5+",
        "G": "1",
        "Special": []
    },
    "Weapons": [
        {
            "Name": "Oculus Beam Array",
            "Arc": "F/S",
            "Att": 3,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Scald-1"
            ]
        },
        {
            "Name": "Oculus Beam Phalanx",
            "Arc": "F/S",
            "Att": 4,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Scald-1",
                "Volley-2"
            ]
        },
        {
            "Name": "Furnace Fangs",
            "Arc": "FN",
            "Att": 6,
            "Lock": "2+",
            "DMG": 1,
            "Type": "E",
            "Special": [
                "Burnthrough-1",
                "Crippling-Fire",
                "Focused"
            ]
        }
    ],
    "Load": [],
    "Rules": [
        {
            "Name": "Keel Refit",
            "Text": "This Ship may take a Cloaking Keel for +15 points, gaining Stealth and Cloak-2, or an Engine Upgrade for +25 points increasing Thrust by 3\"."
        }
    ],
    "Upgrades": [
        {
            "Name": "Keel Refit",
            "Min": 0,
            "Max": 1,
            "Options": [
                {
                    "Name": "Cloaking Keel",
                    "Cost": 15,
                    "Effects": [
                        {
                            "Target": "Special",
                            "Type": "append",
                            "Value": "Stealth"
                        },
                        {
                            "Target": "Special",
                            "Type": "append",
                            "Value": "Cloak-2"
                        }
                    ]
                },
                {
                    "Name": "Engine Upgrade",
                    "Cost": 25,
                    "Effects": [
                        {
                            "Target": "Thrust",
                            "Type": "add",
                            "Value": 3
                        }
                    ]
                }
            ]
        }
    ],
    "KnownShips": [],
    "Flavour": ""
}

=== Kemp-J/dfc-data/Data/Scourge/nephilim.json
{
    "Class": "Nephilim",
    "Type": "Super Battleship",
    "Points": 255,
    "Tonnage": "H",
    "BaseSize": 50,
    "Profile": {
        "Thrust": 6,
        "Scan": 8,
        "Sig": 10,
        "Hull": 20,
        "ES": "3+",
        "KS": "4+",
        "BS": "5+",
        "G": "1",
        "Special": []
    },
    "Weapons": [
        {
            "Name": "Heavy Plasma Beam Triad",
            "Arc": "F",
            "Att": 3,
            "Lock": "3+",
            "DMG": 3,
            "Type": "E",
            "Special": [
                "Close Action",
                "Penetrator"
            ]
        },
        {
            "Name": "Furnace Fangs",
            "Arc": "FN",
            "Att": 6,
            "Lock": "2+",
            "DMG": 1,
            "Type": "E",
            "Special": [
                "Burnthrough-1",
                "Crippling-Fire",
                "Focused"
            ]
        },
        {
            "Name": "Furnace Fangs",
            "Arc": "FN",
            "Att": 6,
            "Lock": "2+",
            "DMG": 1,
            "Type": "E",
            "Special": [
                "Burnthrough-1",
                "Crippling-Fire",
                "Focused"
            ]
        },
        {
            "Name": "Oculus Beam Array",
            "Arc": "F/S",
            "Att": 3,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Scald-1"
            ]
        }
    ],
    "Load": [],
    "Rules": [
        {
            "Name": "Keel Options",
            "Text": "This Ship must take either a Cloaking Keel, gaining Stealth and Cloak-2, or an Engine Upgrade for +10 points, increasing Thrust by 3\"."
        }
    ],
    "Upgrades": [
        {
            "Name": "Keel Options",
            "Min": 1,
            "Max": 1,
            "Options": [
                {
                    "Name": "Cloaking Keel",
                    "Cost": 0,
                    "Effects": [
                        {
                            "Target": "Special",
                            "Type": "append",
                            "Value": "Stealth"
                        },
                        {
                            "Target": "Special",
                            "Type": "append",
                            "Value": "Cloak-2"
                        }
                    ]
                },
                {
                    "Name": "Engine Upgrade",
                    "Cost": 10,
                    "Effects": [
                        {
                            "Target": "Thrust",
                            "Type": "add",
                            "Value": 3
                        }
                    ]
                }
            ]
        }
    ],
    "KnownShips": [
        "Void Giant",
        "Elysium's Hammer",
        "The Loss of Victory",
        "Sadness"
    ],
    "Flavour": "With its heavy plasma beam triad, the Nephilim is one of the most fearsome known ships within close action range. These vast energy weapons can core-out the largest opponents with searing plasma. Additionally, its quad furnace fangs and oculus beams enhance this monster's lethality. Lastly, like all Scourge super battleships, the class has been encountered either with stealth capabilities or extra drives, both of which help the Nephilim reach killing range."
}

=== Kemp-J/dfc-data/Data/UCM/babylon.json
{
    "Class": "Babylon",
    "Type": "Super Battleship",
    "Points": 325,
    "Tonnage": "H",
    "BaseSize": 50,
    "Profile": {
        "Thrust": 6,
        "Scan": 10,
        "Sig": 10,
        "Hull": 20,
        "ES": "4+",
        "KS": "3+",
        "BS": "5+",
        "G": "1",
        "Special": []
    },
    "Weapons": [
        {
            "Name": "Python Super Heavy Laser",
            "Arc": "FN",
            "Att": 5,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Bloom-2",
                "Burnthrough-2",
                "Flash-1",
                "Focused"
            ]
        },
        {
            "Name": "UF-6400 Mass Driver Turret Triad",
            "Arc": "F/S",
            "Att": 6,
            "Lock": "3+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Critical-1"
            ]
        },
        {
            "Name": "UF-4200 Mass Driver Turrets",
            "Arc": "F/S",
            "Att": 4,
            "Lock": "4+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Fusillade-2"
            ]
        },
        {
            "Name": "UF-4200 Mass Driver Turrets",
            "Arc": "F/S",
            "Att": 4,
            "Lock": "4+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Fusillade-2"
            ]
        },
        {
            "Name": "Cobra Heavy Laser Pair",
            "Arc": "FN",
            "Att": 6,
            "Lock": "3+",
            "DMG": 1,
            "Type": "E",
            "Special": [
                "Burnthrough-2",
                "Flash-2",
                "Focused"
            ],
            "Cost": 5,
            "Replaces": [
                "UF-4200 Mass Driver Turrets",
                "UF-4200 Mass Driver Turrets"
            ],
            "RuleName": "Laser Refit"
        }
    ],
    "Load": [
        {
            "Load": "Fighters & Bombers",
            "Launch": 4,
            "Special": [
                "Alt-1"
            ]
        },
        {
            "Load": "Heavy Bombers",
            "Launch": 3,
            "Special": [
                "Alt-1"
            ]
        },
        {
            "Load": "Medium Torpedo",
            "Launch": 1,
            "Special": [
                "Limited-2"
            ]
        }
    ],
    "Rules": [
        {
            "Name": "Laser Refit",
            "Text": "This Ship may take a Laser Refit for +5 points, replacing both of its UF-4200 Mass Driver Turrets with a single Cobra Heavy Laser Pair."
        }
    ],
    "KnownShips": [
        "Babylon",
        "Alexander the Great",
        "Gaugamela",
        "Nebuchadnezzar"
    ],
    "Flavour": "The Babylon shares the substantial armaments and fleet carrier capacity as its sister class, the Byzantium super battleship, but the Babylon elevates its anti-shipping capabilities by replacing the bombardment turrets with UF-6400 mass driver turrets. This was only possible due to the UCM's latest battleship superstructure and its enhanced power generators. Together, its extensive weapons suite is enough to obliterate any foe."
}

=== Kemp-J/dfc-data/Data/Scourge/beelzebub.json
{
    "Class": "Beelzebub",
    "Type": "Battleship",
    "Points": 255,
    "Tonnage": "H",
    "BaseSize": 50,
    "Profile": {
        "Thrust": 8,
        "Scan": 8,
        "Sig": 10,
        "Hull": 20,
        "ES": "3+",
        "KS": "4+",
        "BS": "5+",
        "G": "1",
        "Special": []
    },
    "Weapons": [
        {
            "Name": "Mega Plasma Lance Battery",
            "Arc": "F/S",
            "Att": 3,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Calibre-H/C",
                "Reave-2",
                "Volley-2"
            ]
        },
        {
            "Name": "Oculus Beam Array",
            "Arc": "F/S",
            "Att": 3,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Scald-1"
            ]
        },
        {
            "Name": "Furnace Fangs",
            "Arc": "FN",
            "Att": 6,
            "Lock": "2+",
            "DMG": 1,
            "Type": "E",
            "Special": [
                "Burnthrough-1",
                "Crippling-Fire",
                "Focused"
            ]
        }
    ],
    "Load": [
        {
            "Load": "Fighters & Bombers",
            "Launch": 3,
            "Special": []
        }
    ],
    "Rules": [
        {
            "Name": "Keel Refit",
            "Text": "This Ship may take a Cloaking Keel for +15 points, gaining Stealth and Cloak-2, or an Engine Upgrade for +25 points increasing Thrust by 3\"."
        }
    ],
    "Upgrades": [
        {
            "Name": "Keel Refit",
            "Min": 0,
            "Max": 1,
            "Options": [
                {
                    "Name": "Cloaking Keel",
                    "Cost": 15,
                    "Effects": [
                        {
                            "Target": "Special",
                            "Type": "append",
                            "Value": "Stealth"
                        },
                        {
                            "Target": "Special",
                            "Type": "append",
                            "Value": "Cloak-2"
                        }
                    ]
                },
                {
                    "Name": "Engine Upgrade",
                    "Cost": 25,
                    "Effects": [
                        {
                            "Target": "Thrust",
                            "Type": "add",
                            "Value": 3
                        }
                    ]
                }
            ]
        }
    ],
    "KnownShips": [],
    "Flavour": ""
}

=== Kemp-J/dfc-data/Data/Bioficer/sierra.json
{
    "Class": "Sierra",
    "Type": "Pocket Battleship",
    "Points": 185,
    "Tonnage": "H",
    "BaseSize": 50,
    "Profile": {
        "Thrust": 8,
        "Scan": 10,
        "Sig": 4,
        "Hull": 14,
        "ES": "4+",
        "KS": "4+",
        "BS": "5+",
        "G": "1",
        "Special": []
    },
    "Weapons": [
        {
            "Name": "Hyper Lightvice",
            "Arc": "F/S",
            "Att": 5,
            "Lock": "2+",
            "DMG": 3,
            "Type": "K",
            "Special": [
                "Bloom-1",
                "Close Action",
                "Focused",
                "Scald-1"
            ]
        },
        {
            "Name": "Decon Blaster",
            "Arc": "FN",
            "Att": 3,
            "Lock": "3+",
            "DMG": 1,
            "Type": "E",
            "Special": []
        },
        {
            "Name": "Decon Blaster",
            "Arc": "FN",
            "Att": 3,
            "Lock": "3+",
            "DMG": 1,
            "Type": "E",
            "Special": []
        }
    ],
    "Load": [],
    "Rules": [
        {
            "Name": "Feature Carrier",
            "Text": "At the start of the game, before players deploy, choose from the Gravitational Arc or Ghost Orb Tower Deployable Feature. This Ship starts the game carrying the chosen Deployable Feature."
        }
    ],
    "KnownShips": [],
    "Flavour": ""
}

=== Kemp-J/dfc-data/Data/PHR/ikarus.json
{
    "Class": "Ikarus",
    "Type": "Vanguard Carrier",
    "Points": 125,
    "Tonnage": "M",
    "BaseSize": 40,
    "Profile": {
        "Thrust": 8,
        "Scan": 8,
        "Sig": 6,
        "Hull": 11,
        "ES": "3+",
        "KS": "4+",
        "BS": "-",
        "G": "1-2",
        "Special": [
            "Vanguard-4\""
        ]
    },
    "Weapons": [
        {
            "Name": "Medium Calibre Broadside",
            "Arc": "B",
            "Att": 3,
            "Lock": "4+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Fusillade-1",
                "Volley-2"
            ]
        },
        {
            "Name": "Medium Calibre Turret",
            "Arc": "F",
            "Att": 1,
            "Lock": "4+",
            "DMG": 2,
            "Type": "K",
            "Special": []
        }
    ],
    "Load": [
        {
            "Load": "Fighters & Bombers",
            "Launch": 2,
            "Special": []
        },
        {
            "Load": "Mines",
            "Launch": 2,
            "Special": [],
            "Cost": 10,
            "Replaces": [
                "Fighters & Bombers"
            ],
            "RuleName": "Minelayer"
        }
    ],
    "Rules": [
        {
            "Name": "Minelayer",
            "Text": "This ship may replace its Fighters & Bombers with Mines for +10 pts."
        }
    ],
    "KnownShips": [
        "Red Cliffs",
        "Plato",
        "Tower of Knowledge",
        "Dark Prince"
    ],
    "Flavour": "The Ikarus class is an unusual ship as it carries the rare designation of vanguard carrier, a variant of the more common fleet carrier. Vessels of this designation have a strike craft launch capacity but are more often found at the front and centre of a battle line rather than at the rear, since they also carry significant regular firepower. The Ikarus includes two reduced medium mass driver broadsides in addition to a traversable front turret – weapons chosen for their universally dangerous output.\nWhile unleashing its many mass drivers against enemy ships, the Ikarus can also launch waves of fighters and bombers. Its typically forward position allows these long range assets to strike at enemy rearguard elements, making the class a highly useful tool much prized by PHR admirals. A vanguard positioning also makes it ideal for deploying fighter screens to protect ships in the forefront of the formation. Its lower launch capacity also allows the usually limited number of available pilots to be spread more evenly throughout a fleet rather than concentrated in dedicated carriers, if the battle plan calls for it."
}

=== Kemp-J/dfc-data/Data/UCM/seattle.json
{
    "Class": "Seattle",
    "Type": "Fleet Carrier",
    "Points": 116,
    "Tonnage": "M",
    "BaseSize": 40,
    "Profile": {
        "Thrust": 8,
        "Scan": 6,
        "Sig": 6,
        "Hull": 10,
        "ES": "4+",
        "KS": "3+",
        "BS": "-",
        "G": "1",
        "Special": []
    },
    "Weapons": [
        {
            "Name": "UF-6400 Mass Driver Turrets",
            "Arc": "F/S",
            "Att": 4,
            "Lock": "3+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Critical-1"
            ]
        }
    ],
    "Load": [
        {
            "Load": "Fighters & Bombers",
            "Launch": 2,
            "Special": []
        },
        {
            "Load": "Mines",
            "Launch": 2,
            "Special": [],
            "Cost": 10,
            "Replaces": [
                "Fighters & Bombers"
            ],
            "RuleName": "Minelayer"
        }
    ],
    "Rules": [
        {
            "Name": "Minelayer",
            "Text": "This ship may replace its Fighters & Bombers with Mines for +10 pts."
        }
    ],
    "KnownShips": [
        "Ark Royal",
        "Midway",
        "Enterprise",
        "Waning Tide"
    ],
    "Flavour": "The Seattle class is multi-role cruiser tonnage carrier for void-capable fighters and bombers. Its capacious hangars accommodate a large number of these nimble strike craft while the ship itself is armed with four UF-6400 mass drivers in a pair of turrets for direct ship-ship engagements. These characteristics make the Seattle a flexible and valuable asset in almost any engagement despite its lower launch capacity compared to some of the more dedicated carriers of other races.\nAs a fleet carrier, the Seattle is often positioned towards the rear of the battle, where its strike craft can support the main formation while it stays clear of the engagement. However, since it sports reasonable anti-ship firepower and launch assets have low power requirements, it is possible for the Seattle to use both while conducting advanced manoeuvres. This makes the Seattle a potent tool in the hands of a skilled captain whose carefully directed aggression and quick thinking are rewarded with disproportionate damage to the enemy."
}
